In [1]:
'''
Using Doc2Vec
Purpose: Fetch data, create docvec vector, get cosine similarities, form similarity sets
Input: Text data
Output: Similarity sets
'''

import re
import pandas as pd
from nltk.corpus import stopwords 
filePath= "F:/Amrita Mtech/Glisten Internship/Work/Travel Book/Sinhagad Wiki Text.txt"

#get data from txt file
file = open(filePath, "r")
doclist = [ line for line in file ]
docstr = '' . join(doclist)
sentences = re.split(r'[.!?]', docstr)
 
stopwords = set(stopwords.words('english'))     
for i, sentence in enumerate(sentences):
        tokenized= []
        for word in sentence.split(' '):
            if (word not in stopwords or word==""): 
                word = word.split('.')[0]
                word = word.lower()
                tokenized.append(word)
        sentences[i] = tokenized
print("Number of sentences are: ", len(sentences))      
print("\n The sentence vector is: ")
print(sentences)

df_sentences=pd.DataFrame()
df_sentences["Sentence"]=sentences
df_sentences["id"]=df_sentences.index
i=0
for each in df_sentences["Sentence"]:
        str1=" "
        df_sentences["Sentence"][i]=str1.join(each)
        i=i+1
print(df_sentences)


Number of sentences are:  61

 The sentence vector is: 
[['sinhagad', 'hill', 'fortress', 'located', 'around', '35', 'km', 'southwest', 'city', 'pune,', 'india'], ['', 'some', 'information', 'available', 'fort', 'suggests', 'fort', 'could', 'built', '2000', 'years', 'ago'], ['', 'the', 'caves', 'carvings', 'kaundinyeshwar', 'temple', 'stand', 'proofs'], ['previously', 'known', 'kondhana,', 'fort', 'site', 'many', 'battles,', 'notably', 'battle', 'sinhagad', '1670'], ['', 'perched', 'isolated', 'cliff', 'bhuleswar', 'range', 'sahyadri', 'mountains,', 'fort', 'situated', 'hill', '760', 'metres', 'ground', '1,312', 'metres', 'mean', 'sea', 'level'], ['the', 'sinhagad', "(lion's", 'fort)', 'strategically', 'built', 'provide', 'natural', 'protection', 'due', 'steep', 'slopes'], ['', 'the', 'walls', 'bastions', 'constructed', 'key', 'places'], ['', 'there', 'two', 'gates', 'enter', 'fort,', 'kalyan', 'darwaza', 'pune', 'darwaza', 'positioned', 'south', 'east', 'north-east', 'ends', 'respecti

c:\python37\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


                                             Sentence  id
0   sinhagad hill fortress located around 35 km so...   0
1    some information available fort suggests fort...   1
2    the caves carvings kaundinyeshwar temple stan...   2
3   previously known kondhana, fort site many batt...   3
4    perched isolated cliff bhuleswar range sahyad...   4
5   the sinhagad (lion's fort) strategically built...   5
6           the walls bastions constructed key places   6
7    there two gates enter fort, kalyan darwaza pu...   7
8    the fort also strategically located centre st...   8
9   the sinhgad fort initially known "kondhana" sa...   9
10   the kaundinyeshwar temple coupled caves carvi...  10
11   it seized muhammad bin tughlaq koli king nag ...  11
12  shahaji bhosale, commander ibrahim adil shah i...  12
13   his son chhatrapati shivaji maharaj, refused ...  13
14   chhatrapati shivaji maharaj gained control ko...  14
15   bapuji mudgal deshpande played key role activity  15
16   adil shah

In [5]:
##Vector Formation :2 Doc 2 vec
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
import numpy as np
import itertools

tagged_data = [TaggedDocument(d, [i]) for i, d in enumerate(sentences)]
docmodel = Doc2Vec(tagged_data, vector_size=20, window=2, min_count=1, workers=4, epochs = 100)

arrays1 = []
for i in sentences:
    vector = docmodel.infer_vector(i)
    arrays1.append(vector)
print(arrays1)

'''
arrays1 = []
for senetnce in sentences:
    list1=[]
    list1=docmodel[senetnce]
    print(senetnce)
    print(docmodel[senetnce])
    flattened_list = [y for x in list1 for y in x]
    print(flattened_list)
    arrays1.append(flattened_list)

for l in range(0,61):
    list1=[]
    list1=list(itertools.chain.from_iterable( arrays1[l]))
    arrays1[l]=list1

print(arrays1)
print(len(arrays1))   
'''

[array([ 0.12028562, -0.2172706 , -0.2569246 ,  0.7843774 , -0.13835362,
        0.13972367, -0.5430778 , -0.61384684, -0.6880197 ,  0.6485582 ,
       -0.53871876, -0.82551813, -0.61858547,  0.9175764 ,  0.09066178,
       -1.5400399 ,  0.44491458, -1.9724327 ,  0.2546135 ,  0.6264215 ],
      dtype=float32), array([ 0.11389291, -0.32716468, -0.2665016 ,  0.72524863, -0.00997755,
        0.18844442, -0.29989746, -0.67171276, -0.6604791 ,  0.60717493,
       -0.5722254 , -0.6848828 , -0.5679129 ,  0.80583894,  0.01588741,
       -1.3927993 ,  0.43815327, -1.7900403 ,  0.25945538,  0.58279884],
      dtype=float32), array([ 0.05942529, -0.2694548 , -0.15404613,  0.53582364, -0.05860619,
        0.13054796, -0.2395774 , -0.41119677, -0.49220607,  0.48701626,
       -0.34552345, -0.4510326 , -0.45052928,  0.5844114 ,  0.07124989,
       -1.0066198 ,  0.2601354 , -1.3159958 ,  0.24455823,  0.39380935],
      dtype=float32), array([ 0.13610248, -0.20304593, -0.2727904 ,  0.809687  , -0.1575

'\narrays1 = []\nfor senetnce in sentences:\n    list1=[]\n    list1=docmodel[senetnce]\n    print(senetnce)\n    print(docmodel[senetnce])\n    flattened_list = [y for x in list1 for y in x]\n    print(flattened_list)\n    arrays1.append(flattened_list)\n\n\nfor l in range(0,61):\n    list1=[]\n    list1=list(itertools.chain.from_iterable( arrays1[l]))\n    arrays1[l]=list1\n\nprint(arrays1)\nprint(len(arrays1))   \n'

In [6]:
#Cosine simillarities: 61X61 Doc2Vec
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
import pandas as pd

A_sparse1 = sparse.csr_matrix(arrays1)
similarities_docvec = cosine_similarity(A_sparse1)
print('pairwise dense output:\n {}\n'.format(similarities_docvec))

#get similarities in dataframe
df1=pd.DataFrame(data=similarities_docvec)
print(df1)

pairwise dense output:
 [[1.         0.9944821  0.99426526 ... 0.9966249  0.9956769  0.96162665]
 [0.9944821  1.         0.9966183  ... 0.99270314 0.9929105  0.95447546]
 [0.99426526 0.9966183  0.99999994 ... 0.99570507 0.9948901  0.95866615]
 ...
 [0.9966249  0.99270314 0.99570507 ... 0.99999994 0.99418265 0.95912194]
 [0.9956769  0.9929105  0.9948901  ... 0.99418265 1.         0.9547514 ]
 [0.96162665 0.95447546 0.95866615 ... 0.95912194 0.9547514  1.        ]]

          0         1         2         3         4         5         6   \
0   1.000000  0.994482  0.994265  0.996555  0.993155  0.997034  0.995927   
1   0.994482  1.000000  0.996618  0.995187  0.992585  0.996186  0.996510   
2   0.994265  0.996618  1.000000  0.995501  0.995856  0.994085  0.996502   
3   0.996555  0.995187  0.995501  1.000000  0.993779  0.997373  0.996657   
4   0.993155  0.992585  0.995856  0.993779  1.000000  0.991761  0.993618   
5   0.997034  0.996186  0.994085  0.997373  0.991761  1.000000  0.998180   

In [9]:
#Get Similarity sets
import pandas as pd

def get_similarityset(threshold):
    dictionary={} 
    dictionary=df1.to_dict(orient='records')
    Similaritysets=[]   
    list1=[]
    SimilarityDict=[]
    count=0
    for each in dictionary:
        list3=[]
        ss1=[]
        Sd1={}
        for key, value in sorted(each.items(), key=lambda item: item[1], reverse=True):
            if (key!=count):
                list3.append(key)
                if (value>= threshold):
                    ss1.append(value)
                    Sd1.update({key:value})    
        list1.append(list3)
        Similaritysets.append(ss1)
        if(bool(Sd1)):
            SimilarityDict.append(Sd1)
        count=count+1
    #print(Similaritysets)
    #print(SimilarityDict)
    location=1
    simlist=[]
    for i in SimilarityDict:
        list_keys=[k for k in i]
        list_values=[v for v in i.values()]
        list_key_value=[[k,v] for k,v in i.items()]
        #print(list_key_value)
        simlist.append(list_key_value)
    print("Lenghth of similarity sets: " ,len(SimilarityDict))
    #print(simlist)
    df_similarities=pd.DataFrame(simlist)
    print(df_similarities.head())

print("With avg Word to vec: ")    
get_similarityset(0.8)

With avg Word to vec: 
Lenghth of similarity sets:  61
                 0                 1                 2                3   \
0  [42, 0.99819356]   [29, 0.9972991]   [41, 0.9972474]   [5, 0.9970342]   
1   [10, 0.9979581]   [47, 0.9977654]   [17, 0.9972878]  [43, 0.9968066]   
2   [38, 0.9990498]   [44, 0.9979117]  [10, 0.99771583]  [53, 0.9976167]   
3  [11, 0.99830765]  [50, 0.99823874]   [51, 0.9981145]  [41, 0.9977201]   
4   [51, 0.9966496]  [44, 0.99655735]   [9, 0.99616826]  [30, 0.9960775]   

                 4                 5                 6                 7   \
0   [36, 0.9968241]  [20, 0.99667376]  [52, 0.99665236]   [58, 0.9966249]   
1   [44, 0.9967198]    [2, 0.9966183]   [6, 0.99650973]   [37, 0.9964673]   
2  [50, 0.99753934]  [17, 0.99746495]  [25, 0.99711716]  [43, 0.99709177]   
3  [55, 0.99752104]  [38, 0.99745464]   [5, 0.99737316]  [17, 0.99712396]   
4   [11, 0.9960542]  [21, 0.99601096]   [2, 0.99585646]   [50, 0.9957983]   

                 8       