In [2]:
import re
import pandas as pd
filePath= "F:/Amrita Mtech/Glisten Internship/Work/Travel Book/Sinhagad Wiki Text.txt"

#get data from txt file
file = open(filePath, "r")
doclist = [ line for line in file ]
docstr = '' . join(doclist)
sentences = re.split(r'[.!?]', docstr)
    
for i, sentence in enumerate(sentences):
        tokenized= []
        for word in sentence.split(' '):
                word = word.split('.')[0]
                word = word.lower()
                tokenized.append(word)
        sentences[i] = tokenized
print("Number of sentences are: ", len(sentences))      
print("\n The sentence vector is: ")
print(sentences)

df_sentences=pd.DataFrame()
df_sentences["Sentence"]=sentences
df_sentences["id"]=df_sentences.index
i=0
for each in df_sentences["Sentence"]:
        str1=" "
        df_sentences["Sentence"][i]=str1.join(each)
        i=i+1
print(df_sentences)


Number of sentences are:  61

 The sentence vector is: 
[['sinhagad', 'is', 'a', 'hill', 'fortress', 'located', 'at', 'around', '35', 'km', 'southwest', 'of', 'the', 'city', 'of', 'pune,', 'india'], ['', 'some', 'of', 'the', 'information', 'available', 'at', 'this', 'fort', 'suggests', 'that', 'the', 'fort', 'could', 'have', 'been', 'built', '2000', 'years', 'ago'], ['', 'the', 'caves', 'and', 'the', 'carvings', 'in', 'the', 'kaundinyeshwar', 'temple', 'stand', 'as', 'proofs', 'for', 'the', 'same'], ['previously', 'known', 'as', 'kondhana,', 'the', 'fort', 'had', 'been', 'the', 'site', 'of', 'many', 'battles,', 'most', 'notably', 'the', 'battle', 'of', 'sinhagad', 'in', '1670'], ['', 'perched', 'on', 'an', 'isolated', 'cliff', 'of', 'the', 'bhuleswar', 'range', 'in', 'the', 'sahyadri', 'mountains,', 'the', 'fort', 'is', 'situated', 'on', 'a', 'hill', 'about', '760', 'metres', 'above', 'ground', 'and', '1,312', 'metres', 'above', 'mean', 'sea', 'level'], ['the', 'sinhagad', "(lion's", '

c:\python37\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


                                             Sentence  id
0   sinhagad is a hill fortress located at around ...   0
1    some of the information available at this for...   1
2    the caves and the carvings in the kaundinyesh...   2
3   previously known as kondhana, the fort had bee...   3
4    perched on an isolated cliff of the bhuleswar...   4
5   the sinhagad (lion's fort) was strategically b...   5
6    the walls and bastions were constructed only ...   6
7    there are two gates to enter the fort, the ka...   7
8    the fort was also strategically located at th...   8
9   the sinhgad fort was initially known as "kondh...   9
10   the kaundinyeshwar temple coupled with the ca...  10
11   it was seized by muhammad bin tughlaq from th...  11
12  shahaji bhosale, as the commander of ibrahim a...  12
13   his son chhatrapati shivaji maharaj, refused ...  13
14   chhatrapati shivaji maharaj gained control of...  14
15   bapuji mudgal deshpande played a key role in ...  15
16   adil shah

In [3]:
##Vector Formation : 1 Word vector
from gensim.models import word2vec
model = word2vec.Word2Vec(sentences,min_count=1)
len(model.wv.vocab)

#For averaging
import numpy as np

def buildWordVector(text):
    ##vec = np.zeros(size).reshape((1, size))
    vec=0
    count = 0
    for word in text:
        #vec =vec + model[word].reshape((1, size))
        vec =vec + model[word]
        count =count+ 1.

    if count != 0:
        vec =vec/count
    return vec

arrays = []
for sentence in sentences:
    arrays.append(buildWordVector(sentence))
print(arrays)
print(len(arrays))

[array([-3.9018582e-06,  4.6879431e-04,  3.5559471e-05, -3.5476446e-04,
        4.5904977e-04,  4.7898374e-04, -6.4556621e-04, -9.9069870e-04,
       -1.1689190e-04, -1.1181973e-03,  3.4814267e-04, -1.3859870e-04,
       -1.0567801e-03, -2.7448445e-04,  1.2591343e-03, -6.3069013e-04,
       -1.0208722e-03, -7.3455158e-05, -1.0310402e-03,  3.8231027e-04,
        7.2863681e-04, -9.8044937e-04, -5.0605088e-04,  1.3048953e-03,
       -1.1258232e-03, -9.9855394e-04,  9.7187236e-04, -4.4791668e-04,
       -1.5507890e-04, -1.0121192e-03, -1.1275491e-03, -1.7051473e-03,
        3.1901427e-04,  4.4223349e-04, -1.2830320e-04, -4.9554470e-05,
        6.9604802e-04,  1.0614198e-03,  5.8286986e-04, -1.1028887e-03,
       -8.3828479e-04, -7.7856726e-05,  1.3986655e-03,  1.8839927e-04,
        2.3286606e-04,  1.4014136e-03, -1.1154630e-03,  9.1063924e-04,
       -8.3006738e-04, -7.4395811e-04,  1.2074282e-04,  6.9789577e-04,
        8.2654302e-04,  5.1016617e-04, -1.5647445e-03, -1.4171642e-03,
     

c:\python37\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app


In [4]:
#Cosine simillarities: 61X61 word2vec
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
import pandas as pd

A_sparse = sparse.csr_matrix(arrays)

similarities_wordvec = cosine_similarity(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities_wordvec))

#get similarities in dataframe
df=pd.DataFrame(data=similarities_wordvec)
print(df)

pairwise dense output:
 [[1.         0.44998863 0.35455447 ... 0.33336043 0.3156405  0.05907744]
 [0.44998863 1.0000001  0.5309165  ... 0.4773199  0.4694065  0.3043014 ]
 [0.35455447 0.5309165  1.         ... 0.58407634 0.74215615 0.29062477]
 ...
 [0.33336043 0.4773199  0.58407634 ... 1.0000001  0.5020481  0.16578667]
 [0.3156405  0.4694065  0.74215615 ... 0.5020481  0.9999999  0.29990828]
 [0.05907744 0.3043014  0.29062477 ... 0.16578667 0.29990828 1.0000001 ]]

          0         1         2         3         4         5         6   \
0   1.000000  0.449989  0.354554  0.482238  0.424006  0.279346  0.216188   
1   0.449989  1.000000  0.530917  0.609176  0.535557  0.293547  0.406500   
2   0.354554  0.530917  1.000000  0.657415  0.536068  0.140288  0.446935   
3   0.482238  0.609176  0.657415  1.000000  0.529101  0.257035  0.395447   
4   0.424006  0.535557  0.536068  0.529101  1.000000  0.265870  0.529442   
5   0.279346  0.293547  0.140288  0.257035  0.265870  1.000000  0.243281   

In [33]:
#Get Similarity sets
import pandas as pd

def get_similarityset(threshold):
    dictionary={} 
    dictionary=df.to_dict(orient='records')

    Similaritysets=[]   
    list1=[]
    SimilarityDict=[]
    for each in dictionary:
        list3=[]
        ss1=[]
        Sd1={}
        for key, value in sorted(each.items(), key=lambda item: item[1], reverse=True):
            list3.append(key)
            if (value>= threshold):
                ss1.append(value)
                Sd1.update({key:value})
        list1.append(list3)
        Similaritysets.append(ss1)
        SimilarityDict.append(Sd1)

    #print(Similaritysets)
    print(SimilarityDict)
    print("Lenghth of similarity sets: " ,len(SimilarityDict))

print("With avg Word to vec: ")    
get_similarityset(0.5)

With avg Word to vec: 
[{0: 1.0, 34: 0.5876505, 40: 0.5876027, 39: 0.53801703, 47: 0.5246607}, {1: 1.0000001, 10: 0.68766874, 47: 0.6175186, 39: 0.61147076, 3: 0.60917574, 52: 0.58822304, 40: 0.5627225, 23: 0.55669755, 14: 0.5485564, 34: 0.5403618, 4: 0.5355573, 2: 0.5309165, 8: 0.5224464, 19: 0.51785284}, {2: 1.0, 22: 0.7646875, 10: 0.75331354, 23: 0.7512212, 32: 0.7488899, 59: 0.74215615, 52: 0.72046745, 7: 0.7172903, 34: 0.71294445, 46: 0.7091609, 19: 0.70872265, 14: 0.6820855, 40: 0.6810719, 39: 0.6775139, 30: 0.6770404, 45: 0.6749561, 3: 0.6574149, 9: 0.6453965, 12: 0.6065011, 25: 0.59609604, 13: 0.5915867, 58: 0.58407634, 47: 0.54796076, 44: 0.53824764, 4: 0.53606766, 1: 0.5309165, 29: 0.5081431, 11: 0.50131506}, {3: 0.99999976, 40: 0.81349474, 34: 0.78914297, 39: 0.7638657, 19: 0.72332317, 22: 0.6851619, 58: 0.6836981, 2: 0.6574149, 25: 0.6552285, 10: 0.64580774, 47: 0.6452454, 23: 0.64016336, 46: 0.63337785, 59: 0.6320223, 8: 0.6297273, 14: 0.62951404, 9: 0.62647873, 12: 0.6183

In [35]:
##Vector Formation :2 Doc 2 vec
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
import numpy as np

tagged_data = [TaggedDocument(d, [i]) for i, d in enumerate(sentences)]
docmodel = Doc2Vec(tagged_data, vector_size=20, window=2, min_count=1, workers=4, epochs = 100)
print(docmodel['Sinhagad'])

arrays1 = []
for senetnce in sentences:
    arrays1.append(docmodel[senetnce])
print(arrays1)
print(len(arrays1))   



KeyError: "tag 'Sinhagad' not seen in training corpus/invalid"

In [32]:
#Cosine simillarities: 61X61 Doc2Vec
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
import pandas as pd

A_sparse1 = sparse.csr_matrix(arrays1[])

similarities_docvec = cosine_similarity(A_sparse1)
print('pairwise dense output:\n {}\n'.format(similarities_docvec))

#get similarities in dataframe
df1=pd.DataFrame(data=similarities_docvec)
print(df1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()